name: <%= File.basename(Dir.pwd) %>
on_project_start:
  - brew services start postgres
windows:
  - app:
      panes:
        - bundle exec guard
        - rerun -i 'spec/*' bundle exec rackup
        -
  - queues:
      panes:
        - que --log-level debug --queue mailer --queue lehrer --worker-count 2 ./config/que.rb
        -
  - db:
      panes:
        - bundle exec sequel $DB
        - psql $DB
        -
