name: <%= File.basename(Dir.pwd) %>
windows:
  - app:
      panes:
        - bundle exec guard
        - rerun -i 'spec/*' bundle exec rackup
        -
  - db:
      panes:
        - bundle exec sequel $DB
        - psql $DB
        -
